Offline python package download suing requirements file
IBM/operator-collection-sdk pull request #49
Opened 2023-07-26 21:20 UTC by zohiba

2023-07-28 17:35 UTC, freemanlatrell requested changes

2023-07-28 17:43 UTC, zohiba commented on ibm/operator_collection_sdk/playbooks/create_offline_requirements.yml
> +      ignore_errors: true
I can remove this from both tasks

2023-07-28 17:43 UTC, zohiba commented on ibm/operator_collection_sdk/playbooks/create_offline_requirements.yml
> +      ignore_errors: true
I saw this was there in the `Download local dependencies` section and hence added it here as well

2023-07-31 15:35 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_offline_requirements.yml
> +      ignore_errors: true
@zohiba Yes, that's because the validation happens in a later task

2023-07-31 15:35 UTC, freemanlatrell approved these changes

2023-08-01 22:40 UTC, freemanlatrell approved these changes

2023-08-01 22:40 UTC, merged