Create playbook for zoscb-encrypt tool
IBM/operator-collection-sdk pull request #6
Opened 2023-05-12 16:17 UTC by kberkos-public

This pull request introduces a new feature:
The ability to create a secret using the zoscb-encrypt tool that comes installed in every suboperator pod.

The user needs to supply the information for the credential to be created (username, ssh key, etc.) as well as the name of the operator to install in, and the name of the secret to be created.

2023-05-12 16:18 UTC, kberkos-public commented
Things to do before this is merged:
1. Run the playbook to make sure it works, there is a bug with the encryption tool preventing testing.
2. Run the molecule tests associated with the new playbook
3. Determine if we want to support Github token authentication, since the purpose of this playbook is for airgapped users who might not have access to Github.

2023-05-15 16:26 UTC, freemanlatrell requested changes
Can you also update the playbook name from `create_secret.yml` to `create_credential_secret.yml`

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc exec -n {{ target_namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s
- Remove personal namespace
- `-s /tmp/key` should be `-s /tmp/ssh_key`

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc exec -n {{ namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s {{ssh_
```suggestion
      ansible.builtin.command: "oc exec -n {{ target_namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s /tmp/ssh_key-p {{ passphrase }}"
```

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc exec -n {{ namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s {{ssh_
Also, since this pod contains multiple containers, you should also append the `-c <container-name>` parameter to the command

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc exec -n {{ target_namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -u {{ username }} -s
Since this pod contains multiple containers, you should also append the -c <container-name> parameter to the command

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc exec -n {{ target_namespace }} {{ suboperator_pod_results.resources[0].metadata.name }} -- zoscb-encrypt credential-secret -n {{ secret_name }} -f {{ github_token }
Github token commands can be removed

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +    - name: Create github token secret
Github token commands can be removed

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc cp {{ ssh_key }} {{ suboperator_pod_results.resources[0].metadata.name }}:/tmp/ssh_key"
```suggestion
      ansible.builtin.command: "oc cp {{ ssh_key }} {{ suboperator_pod_results.resources[0].metadata.namespace }}/{{ suboperator_pod_results.resources[0].metadata.name }}:/tmp/ssh_key"
```

2023-05-15 16:26 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/create_secret.yml
> +      ansible.builtin.command: "oc cp {{ ssh_key }} {{ suboperator_pod_results.resources[0].metadata.name }}:/tmp/ssh_key"
The namespace is needed to so that we don't mistakenly attempt to copy to a pod in the incorrect namespace

2023-05-31 21:27 UTC, freemanlatrell requested changes

2023-05-31 21:27 UTC, freemanlatrell commented on ibm/operator_collection_sdk/playbooks/molecule/create_credential_secret/verify.yml
> +    - name: Assert CSV configuration
This verification and all of the verifications above can be removed

2023-06-16 19:43 UTC, freemanlatrell approved these changes

2023-06-16 21:07 UTC, freemanlatrell approved these changes

2023-06-16 21:07 UTC, merged