Adding error handling when initializing collection and it already exist
IBM/operator-collection-sdk pull request #90
Opened 2024-01-31 17:42 UTC by MariandreaMV

fix for issue #89

2024-02-16 15:36 UTC, freemanlatrell approved these changes

2024-02-16 16:39 UTC, freemanlatrell commented
@MariandreaMV I'm currently hitting the error below in the latest test 
![image](https://github.com/IBM/operator-collection-sdk/assets/24191850/17aed375-056a-41f0-b6f8-af057bf19561)

2024-02-16 16:40 UTC, freemanlatrell requested changes
Please see test failure

2024-02-20 16:14 UTC, MariandreaMV commented
I am sorry @freemanlatrell! I forgot to add the `register: result` to create result variable. Thank you so much!

2024-02-21 02:52 UTC, freemanlatrell approved these changes

2024-02-21 02:52 UTC, merged